sudo: required
services:
  - docker

before_install:
  - docker build -t swapnil/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true swapnil/react-test npm test

after_success:
  - docker build -t swapnil/multi-client ./client
  - docker build -t swapnil/multi-server ./server
  - docker build -t swapnil/multi-nginx ./nginx
  - docker build -t swapnil/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push swapnil/multi-client
  - docker push swapnil/multi-server
  - docker push swapnil/multi-nginx
  - docker push swapnil/multi-worker